### ISSUE TITLE
No difference between active and non-active like and dislike icons

### ISSUE THREAD

**Issue by AblingerOscar** [sheeepdev/nordtube#2]
Currently, liked and not-liked upvote buttons have the same color, as do disliked and non-disliked buttons
![image](https://user-images.githubusercontent.com/25868587/115971336-27ddae80-a548-11eb-8e27-9985499f1787.png)

I'm not entirely sure what colors would be best, but I tried nordic14 (#A3BE8C) for upvotes and  nordic11 (#BF616A) for downvotes.
Makes them stand out a bit, but other colors weren't really well differentiable.

![image](https://user-images.githubusercontent.com/25868587/115972398-69715800-a54e-11eb-8176-cfe3e5f0c212.png)

I did that by adding the following CSS:

```css
#like-button.ytd-comment-action-buttons-renderer.style-default-active {
    color: #a3be8c;
}

#dislike-button.ytd-comment-action-buttons-renderer.style-default-active {
    color: #bf616a;
}
```
